services:
  web:
    build: .
    container_name: logger_app
    ports:
      - "5040:5000"
    volumes:
      - ./app:/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/logger_db
    command: ["./wait-for-it.sh", "db", "5432", "--", "python", "main.py"]
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: logger_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: logger_db
    ports:
      - "5448:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: